<b>PYTHON INTRO SETUP</b>
1. Download and Install Datasets: <a href="http://swcarpentry.github.io/python-novice-inflammation/setup/">http://swcarpentry.github.io/python-novice-inflammation/setup/</a>
2. Make sure required libraries are installed in your machine (they should be if you downloaded Anaconda)
3. Run the following in a terminal/shell window:
    * <b>python --version</b>
        * The python version listed should be 3.4 or greater
    * <b>python -c "import numpy, matplotlib, pandas, jupyter, notebook" && echo $?</b>
        * The output of this command should be 0.
        
<p><b>Live Notebook on Git</b></p>
* <a href="https://github.com/nih-fmrif/2017-09-28-NIH-CMN_notebooks/blob/master/building_programs_with_python.ipynb">https://github.com/nih-fmrif/2017-09-28-NIH-CMN_notebooks/blob/master/building_programs_with_python.ipynb</a>

<p><b>jupyter notebook</b></p>

<b>Useful Jupyter Notebook Commands</b>
* <b>Shift + Enter</b> - Execute current cell, select cell below (if there is not a cell below, it will be created)
* <b>Ctrl + Enter</b> - Executes current cell

<b>In command mode (The color bar next to the cell is blue)</b>
* <b>a</b> - insert cell above
* <b>b</b> - insert cell below
* <b>c</b> - copy cell
* <b>v</b> - paste cell
* <b>dd</b> - delete cell
* <b>z</b> - undo last command

In [4]:
weight_kg = 55

In [5]:
print(weight_kg)

55


In [6]:
print('weight in pounds:', 2.2*weight_kg)

weight in pounds: 121.00000000000001


In [8]:
weight_kg = 57.5
print(weight_kg)

57.5


In [9]:
weight_lb = 2.2 * weight_kg
print(weight_lb)

126.50000000000001


In [10]:
%whos

Variable     Type      Data/Info
--------------------------------
matplotlib   module    <module 'matplotlib' from<...>/matplotlib/__init__.py'>
numpy        module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pandas       module    <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
weight_kg    float     57.5
weight_lb    float     126.50000000000001


<b>Magic Command Syntax</b>
* <b>%</b> prefix- Run a single line magic function
* <b>%%</b> prefix - Run a multi-line magic function

<b>Available Magic Commands</b>
<p>
<a href="http://ipython.readthedocs.io/en/stable/interactive/magics.html">http://ipython.readthedocs.io/en/stable/interactive/magics.html</a></p>

In [11]:
import numpy as np

In [12]:
%ls /Users/varadajc/Desktop/python-novice-inflammation/data/

inflammation-01.csv  inflammation-06.csv  inflammation-11.csv
inflammation-02.csv  inflammation-07.csv  inflammation-12.csv
inflammation-03.csv  inflammation-08.csv  small-01.csv
inflammation-04.csv  inflammation-09.csv  small-02.csv
inflammation-05.csv  inflammation-10.csv  small-03.csv


In [13]:
np.loadtxt(fname='/Users/varadajc/Desktop/python-novice-inflammation/data/inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [14]:
data = np.loadtxt(fname='/Users/varadajc/Desktop/python-novice-inflammation/data/inflammation-01.csv', delimiter=',')

In [16]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [17]:
print(type(data))

<class 'numpy.ndarray'>


In [18]:
print(data.dtype)

float64


In [19]:
print(data.shape)

(60, 40)


In [20]:
print('first value in data: ', data[0,0])

first value in data:  0.0


In [21]:
print('middle value: ', data[30,20])

middle value:  13.0


<img src="http://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.png">

In [22]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


In [23]:
print(data[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [24]:
data[78,80]

IndexError: index 78 is out of bounds for axis 0 with size 60

In [25]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]


In [26]:
doubledata = data * 2.0
print(doubledata)

[[ 0.  0.  2. ...,  6.  0.  0.]
 [ 0.  2.  4. ...,  2.  0.  2.]
 [ 0.  2.  2. ...,  4.  2.  2.]
 ..., 
 [ 0.  2.  2. ...,  2.  2.  2.]
 [ 0.  0.  0. ...,  0.  4.  0.]
 [ 0.  0.  2. ...,  2.  2.  0.]]


In [27]:
tripledata = doubledata + data
print(tripledata)

[[ 0.  0.  3. ...,  9.  0.  0.]
 [ 0.  3.  6. ...,  3.  0.  3.]
 [ 0.  3.  3. ...,  6.  3.  3.]
 ..., 
 [ 0.  3.  3. ...,  3.  3.  3.]
 [ 0.  0.  0. ...,  0.  6.  0.]
 [ 0.  0.  3. ...,  3.  3.  0.]]


In [28]:
print(np.mean(data))

6.14875


In [29]:
import time
print(time.ctime())

Thu Sep 28 12:24:22 2017


In [30]:
maxval, minval, stdval = np.max(data), np.min(data), np.std(data)
print('max: ', maxval)
print('min: ', minval)
print('std: ', stdval)

max:  20.0
min:  0.0
std:  4.61383319712


In [31]:
np.max?

In [32]:
help(np.max)

Help on function amax in module numpy.core.fromnumeric:

amax(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the maximum of an array or maximum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See `doc.ufuncs` (Section "Output arguments") for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,


<img src="http://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png">

In [33]:
data.max(axis=1)

array([ 18.,  18.,  19.,  17.,  17.,  18.,  17.,  20.,  17.,  18.,  18.,
        18.,  17.,  16.,  17.,  18.,  19.,  19.,  17.,  19.,  19.,  16.,
        17.,  15.,  17.,  17.,  18.,  17.,  20.,  17.,  16.,  19.,  15.,
        15.,  19.,  17.,  16.,  17.,  19.,  16.,  18.,  19.,  16.,  19.,
        18.,  16.,  19.,  15.,  16.,  18.,  14.,  20.,  17.,  15.,  17.,
        16.,  17.,  19.,  18.,  18.])

In [34]:
data.max(axis=0)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  19.,
        18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,  10.,   9.,   8.,
         7.,   6.,   5.,   4.,   3.,   2.,   1.])

In [35]:
print(np.mean(data, axis=0))

[  0.           0.45         1.11666667   1.75         2.43333333   3.15
   3.8          3.88333333   5.23333333   5.51666667   5.95         5.9
   8.35         7.73333333   8.36666667   9.5          9.58333333
  10.63333333  11.56666667  12.35        13.25        11.96666667
  11.03333333  10.16666667  10.           8.66666667   9.15         7.25
   7.33333333   6.58333333   6.06666667   5.95         5.11666667   3.6
   3.3          3.56666667   2.48333333   1.5          1.13333333
   0.56666667]


In [36]:
word = 'test word'

In [37]:
word[0]

't'

In [38]:
for character in word:
    print(character)

t
e
s
t
 
w
o
r
d


<img src="http://swcarpentry.github.io/python-novice-inflammation/fig/loops_image.png">

In [39]:
word = "test"
word[0] = "a"

TypeError: 'str' object does not support item assignment

In [40]:
my_list = ["a", "b", "c"]
my_list[0] = "d"
print(my_list)

['d', 'b', 'c']
